/* global __APP_BUILD_TIME__ */

/**
 * Automatically injected build timestamp generated by Vite during `npm run build`.
 * No manual version editing needed—every deploy automatically gets a fresh unique ID!
 */
export const APP_VERSION = typeof __APP_BUILD_TIME__ !== 'undefined' ? __APP_BUILD_TIME__ : 'dev';

/**
 * Formats APP_VERSION timestamp into readable string (e.g. "v2.1 (Build 05 Aug 15:54)")
 */
export const getFormattedVersion = () => {
  if (APP_VERSION === 'dev') return 'v2.1 (Dev Mode)';
  const date = new Date(parseInt(APP_VERSION, 10));
  if (isNaN(date.getTime())) return `v2.1 (${APP_VERSION})`;
  const day = String(date.getDate()).padStart(2, '0');
  const monthNames = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Agu', 'Sep', 'Okt', 'Nov', 'Des'];
  const month = monthNames[date.getMonth()];
  const hours = String(date.getHours()).padStart(2, '0');
  const mins = String(date.getMinutes()).padStart(2, '0');
  return `v2.1 (Build ${day} ${month} ${hours}:${mins})`;
};

/**
 * Checks if the current app version differs from the saved version in localStorage.
 */
export const checkAppVersionUpdate = () => {
  try {
    const savedVersion = localStorage.getItem('totools_app_version');
    if (!savedVersion) {
      localStorage.setItem('totools_app_version', APP_VERSION);
      return false;
    }
    return savedVersion !== APP_VERSION;
  } catch (e) {
    return false;
  }
};

/**
 * Marks current APP_VERSION as acknowledged in localStorage.
 */
export const markVersionAsUpdated = () => {
  try {
    localStorage.setItem('totools_app_version', APP_VERSION);
  } catch (e) {}
};

/**
 * Utility to clear all PWA caches, Service Worker registrations,
 * and localStorage/sessionStorage cache items, then reload the app fresh.
 */
export const clearAppCache = async () => {
  try {
    // 1. Unregister Service Workers
    if ('serviceWorker' in navigator) {
      const registrations = await navigator.serviceWorker.getRegistrations();
      for (let registration of registrations) {
        await registration.unregister();
      }
    }

    // 2. Clear Cache Storage
    if ('caches' in window) {
      const cacheNames = await caches.keys();
      await Promise.all(cacheNames.map((name) => caches.delete(name)));
    }

    // 3. Preserve essential preferences while clearing cache
    const currentTheme = localStorage.getItem('totools_theme');

    localStorage.clear();
    sessionStorage.clear();

    localStorage.setItem('totools_app_version', APP_VERSION);
    if (currentTheme) localStorage.setItem('totools_theme', currentTheme);

    // 4. Force Reload Page to fetch fresh build assets
    window.location.href = window.location.origin + '?v=' + APP_VERSION + '&reset=' + Date.now();
  } catch (err) {
    console.error('Gagal menghapus cache:', err);
    window.location.reload();
  }
};
